src/main/java/br/com/seinfra/model/ItemPedido.java
package br.com.seinfra.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonBackReference;

import br.com.seinfra.global.model.GenericBaseModel;

@Entity
@Table(name = "tb_item_pedido", schema = "bdestq")
public class ItemPedido extends GenericBaseModel<Long>{

	@Column(nullable = false, length = 3)
	private Integer quantidade = 1;
	
	@Column(name = "valor_unitario", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorUnitario = BigDecimal.ZERO;
	
	@ManyToOne
	@JoinColumn(name = "produto_id", nullable = false)
	private Produto produto;
	
	@ManyToOne
	@JsonBackReference("itens")
	@JoinColumn(name = "pedido_id", nullable = false)
	private Pedido pedido;

	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	public BigDecimal getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Transient
	public BigDecimal getValorTotal() {
		return this.getValorUnitario().multiply(new BigDecimal(this.getQuantidade()));
	}
	
	@Transient
	public boolean isProdutoAssociado() {
		return this.getProduto() != null && this.getProduto().getId() != null;
	}
	
	@Transient
	public boolean isEstoqueSuficiente() {
		return this.getPedido().isEmitido() || this.getProduto().getId() == null 
			|| this.getProduto().getQuantidadeEstoque() >= this.getQuantidade(); 
	}
	
	@Transient
	public boolean isEstoqueInsuficiente() {
		return !this.isEstoqueSuficiente();
	}

}

src/main/java/br/com/seinfra/model/Pedido.java
package br.com.seinfra.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import br.com.seinfra.global.model.GenericBaseModel;
import br.com.seinfra.model.enums.FormaPagamento;
import br.com.seinfra.model.enums.StatusPedido;

@Entity
@Table(name = "tb_pedido", schema = "bdestq")
public class Pedido extends GenericBaseModel<Long>{

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false)
	private Date dataCriacao;
	
	@Column(columnDefinition = "text")
	private String observacao;
	
	@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_entrega", nullable = false)
	private Date dataEntrega;
	
	@NotNull
	@Column(name = "valor_frete", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorFrete = BigDecimal.ZERO;
	
	@NotNull
	@Column(name = "valor_desconto", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorDesconto = BigDecimal.ZERO;
	
	@NotNull
	@Column(name = "valor_total", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorTotal = BigDecimal.ZERO;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private StatusPedido status = StatusPedido.ORCAMENTO;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "forma_pagamento", nullable = false, length = 20)
	private FormaPagamento formaPagamento;
	
	@NotNull
	@ManyToOne
	@JoinColumn(name = "vendedor_id", nullable = false)
	private Usuario vendedor;
	
	@NotNull
	@ManyToOne
	@JoinColumn(name = "cliente_id", nullable = false)
	private Cliente cliente;
	
	@Embedded
	private EnderecoEntrega enderecoEntrega;
	
	@JsonManagedReference("itens")
	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
	private Set<ItemPedido> itens = new HashSet<>();

	public Pedido() {
		super();
	}

	public Pedido(BigDecimal valorTotal, Date dataCriacao) {
		this.valorTotal = valorTotal;
		this.dataCriacao = dataCriacao;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public Date getDataEntrega() {
		return dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	public BigDecimal getValorFrete() {
		return valorFrete;
	}

	public void setValorFrete(BigDecimal valorFrete) {
		this.valorFrete = valorFrete;
	}

	public BigDecimal getValorDesconto() {
		return valorDesconto;
	}

	public void setValorDesconto(BigDecimal valorDesconto) {
		this.valorDesconto = valorDesconto;
	}

	public BigDecimal getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public StatusPedido getStatus() {
		return status;
	}

	public void setStatus(StatusPedido status) {
		this.status = status;
	}

	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	public Usuario getVendedor() {
		return vendedor;
	}

	public void setVendedor(Usuario vendedor) {
		this.vendedor = vendedor;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public EnderecoEntrega getEnderecoEntrega() {
		return enderecoEntrega;
	}

	public void setEnderecoEntrega(EnderecoEntrega enderecoEntrega) {
		this.enderecoEntrega = enderecoEntrega;
	}

	public Set<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(Set<ItemPedido> itens) {
		this.itens = itens;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}
	
	@Transient
	public boolean isExistente() {
		return !isNovo();
	}
	
	@Transient
	public BigDecimal getValorSubtotal() {
		return this.getValorTotal().subtract(this.getValorFrete()).add(this.getValorDesconto());
	}
	
	public void recalcularValorTotal() {
		BigDecimal total = BigDecimal.ZERO;
		
		total = total.add(this.getValorFrete()).subtract(this.getValorDesconto());
		
		for (ItemPedido item : this.getItens()) {
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}
		
		this.setValorTotal(total);
	}

	public void adicionarItemVazio() {
		if (this.isOrcamento()) {
			Produto produto = new Produto();
			
			ItemPedido item = new ItemPedido();
			item.setProduto(produto);
			item.setPedido(this);
			
			this.getItens().add(item);
		}
	}

	@Transient
	public boolean isOrcamento() {
		return StatusPedido.ORCAMENTO.equals(this.getStatus());
	}

	public void removerItemVazio() {
		ItemPedido primeiroItem = this.getItens().iterator().next();
		
		if (primeiroItem != null && primeiroItem.getProduto().getId() == null) {
			this.getItens().remove(primeiroItem);
		}
	}

	@Transient
	public boolean isValorTotalNegativo() {
		return this.getValorTotal().compareTo(BigDecimal.ZERO) < 0;
	}

	@Transient
	public boolean isEmitido() {
		return StatusPedido.EMITIDO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoEmissivel() {
		return !this.isEmissivel();
	}

	@Transient
	public boolean isEmissivel() {
		return this.isExistente() && this.isOrcamento();
	}

	@Transient
	public boolean isCancelavel() {
		return this.isExistente() && !this.isCancelado();
	}

	@Transient
	private boolean isCancelado() {
		return StatusPedido.CANCELADO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoCancelavel() {
		return !this.isCancelavel();
	}

	@Transient
	public boolean isAlteravel() {
		return this.isOrcamento();
	}
	
	@Transient
	public boolean isNaoAlteravel() {
		return !this.isAlteravel();
	}
	
	@Transient
	public boolean isNaoEnviavelPorEmail() {
		return this.isNovo() || this.isCancelado();
	}

}

src/main/java/br/com/seinfra/controller/PedidoBean.java
package br.com.seinfra.controller;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.validation.constraints.NotBlank;

import org.apache.commons.lang3.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import br.com.seinfra.config.jsf.FacesUtil;
import br.com.seinfra.exception.NegocioException;
import br.com.seinfra.exception.SKU;
import br.com.seinfra.global.controller.GenericBaseBean;
import br.com.seinfra.model.Cliente;
import br.com.seinfra.model.EnderecoEntrega;
import br.com.seinfra.model.ItemPedido;
import br.com.seinfra.model.Pedido;
import br.com.seinfra.model.Produto;
import br.com.seinfra.model.Usuario;
import br.com.seinfra.model.enums.FormaPagamento;
import br.com.seinfra.model.enums.StatusPedido;
import br.com.seinfra.model.filter.PedidoFilter;
import br.com.seinfra.service.ClienteService;
import br.com.seinfra.service.PedidoService;
import br.com.seinfra.service.ProdutoService;
import br.com.seinfra.service.UsuarioService;

@ViewScoped
@Component("pedidoBean")
public class PedidoBean extends GenericBaseBean<PedidoService, Pedido, Long> implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Autowired
	private UsuarioService usuarioaService;
	
	@Autowired
	private ProdutoService produtoService;
	
	@Autowired
	private ClienteService clienteService;
	
	private String sku;
	
	private List<Usuario> vendedores;
	
	private Produto produtoLinhaEditavel;
	
	private PedidoFilter filtro;
	
	private LazyDataModel<Pedido> model;
	
	  @PostConstruct
	    public void init() {
			selecionado = new Pedido();
	    }
	
	public PedidoBean() {
		setTipo("Pedido");
		filtro = new PedidoFilter();
		model = new LazyDataModel<Pedido>() {

			private static final long serialVersionUID = 1L;
			
			@Override
			public List<Pedido> load(int first, int pageSize, String sortField, SortOrder sortOrder, 
					Map<String, Object> filters) {
				
				filtro.setPrimeiroRegistro(first);
				filtro.setQuantidadeRegistros(pageSize);
				filtro.setPropriedadeOrdenacao(sortField);
				filtro.setAscendente(SortOrder.ASCENDING.equals(sortOrder));
				
				setRowCount(servico.quantidadeFiltrados(filtro).intValue());
				
				return servico.pequisar(filtro);
			}
			
		};
	}
	
	public void inicializar() {
		if (this.getSelecionado() == null) {
			limpar();
		}
		
		this.vendedores = this.usuarioaService.vendedores();
		this.getSelecionado().adicionarItemVazio();
		this.recalcularPedido();
	}
	
	public void clienteSelecionado(SelectEvent event) {
		getSelecionado().setCliente((Cliente) event.getObject());
	}
	
	private void limpar() {
		selecionado = new Pedido();
		getSelecionado().setEnderecoEntrega(new EnderecoEntrega());
	}
	
	public void enviarPedido() {
	}
	
	public void novo() {
		inicializar();
		limpar();
	}
	
	public String salvar() {
		this.getSelecionado().removerItemVazio();
		
		try {
			this.selecionado = servico.salvar(this.selecionado);
		
			FacesUtil.addInfoMessage("Pedido salvo com sucesso!");
		} catch (NegocioException ne) {
			FacesUtil.addErrorMessage(ne.getMessage());
		} finally {
			this.selecionado.adicionarItemVazio();
		}
		return "pesquisa";
	}
	
	public void recalcularPedido() {
		if (this.getSelecionado() != null) {
			this.getSelecionado().recalcularValorTotal();
		}
	}
	
	public void carregarProdutoPorSku() {
		if (StringUtils.isNotEmpty(this.sku)) {
			this.produtoLinhaEditavel = this.produtoService.porSku(this.sku);
			this.carregarProdutoLinhaEditavel();
		}
	}
	
	public void carregarProdutoLinhaEditavel() {
		ItemPedido item = this.getSelecionado().getItens().iterator().next();
		
		if (this.produtoLinhaEditavel != null) {
			if (this.existeItemComProduto(this.produtoLinhaEditavel)) {
				FacesUtil.addErrorMessage("Já existe um item no pedido com o produto informado.");
			} else {
				item.setProduto(this.produtoLinhaEditavel);
				item.setValorUnitario(this.produtoLinhaEditavel.getValorUnitario());
				
				this.getSelecionado().adicionarItemVazio();
				this.produtoLinhaEditavel = null;
				this.sku = null;
				
				this.getSelecionado().recalcularValorTotal();
			}
		}
	}
	
	private boolean existeItemComProduto(Produto produto) {
		boolean existeItem = false;
		
		for (ItemPedido item : this.getSelecionado().getItens()) {
			if (produto.equals(item.getProduto())) {
				existeItem = true;
				break;
			}
		}
		return existeItem;
	}

	public List<Produto> completarProduto(String nome) {
		return this.produtoService.porNome(nome);
	}
	
	public void atualizarQuantidade(ItemPedido item, int linha) {
		if (item.getQuantidade() < 1) {
			if (linha == 0) {
				item.setQuantidade(1);
			} else {
				this.getSelecionado().getItens().remove(item);
			}
		}
		
		this.selecionado.recalcularValorTotal();
	}
	
	public FormaPagamento[] getFormasPagamento() {
		return FormaPagamento.values();
	}
	
	public List<Cliente> completarCliente(String nome) {
		return this.clienteService.buscarPorNome(nome);
	}
	
	public void posProcessarXls(Object documento) {
		HSSFWorkbook planilha = (HSSFWorkbook) documento;
		HSSFSheet folha = planilha.getSheetAt(0);
		HSSFRow cabecalho = folha.getRow(0);
		HSSFCellStyle estiloCelula = planilha.createCellStyle();
		Font fonteCabecalho = planilha.createFont();
		
		fonteCabecalho.setColor(IndexedColors.WHITE.getIndex());
		fonteCabecalho.setBold(true);
		fonteCabecalho.setFontHeightInPoints((short) 16);
		
		estiloCelula.setFont(fonteCabecalho);
		estiloCelula.setFillForegroundColor(IndexedColors.BLACK.getIndex());
		estiloCelula.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		
		for (int i = 0; i < cabecalho.getPhysicalNumberOfCells(); i++) {
			cabecalho.getCell(i).setCellStyle(estiloCelula);
		}
	}
	
	public void emitirPedido() {
		this.selecionado.removerItemVazio();
		
		try {
			this.selecionado = this.servico.emitir(this.selecionado);
			
			FacesUtil.addInfoMessage("Pedido emitido com sucesso!");
		} catch (NegocioException ne) {
			FacesUtil.addErrorMessage(ne.getMessage());
		} finally {
			this.selecionado.adicionarItemVazio();
		}
	}
	
	public void cancelarPedido() {
		try {
			this.selecionado = this.servico.cancelar(this.selecionado);
			
			FacesUtil.addInfoMessage("Pedido cancelado com sucesso!");
		} catch (NegocioException ne) {
			FacesUtil.addErrorMessage(ne.getMessage());
		}
	}
	
	public StatusPedido[] getStatuses() {
		return StatusPedido.values();
	}
	
	public PedidoFilter getFiltro() {
		return filtro;
	}

	public LazyDataModel<Pedido> getModel() {
		return model;
	}

	public List<Usuario> getVendedores() {
		return vendedores;
	}
	
	public boolean isEditando() {
		return getSelecionado() != null && getSelecionado().getId() != null;
	}

	public Produto getProdutoLinhaEditavel() {
		return produtoLinhaEditavel;
	}

	public void setProdutoLinhaEditavel(Produto produtoLinhaEditavel) {
		this.produtoLinhaEditavel = produtoLinhaEditavel;
	}

	@SKU
	public String getSku() {
		return sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}
	
	@NotBlank
	public String getNomeCliente() {
		return getSelecionado() != null && getSelecionado().getCliente() != null ? getSelecionado().getCliente().getNome() : null;
	}
	
	public void setNomeCliente(String nome) {
	}
}

src/main/webapp/WEB-INF/template/pedido/BotoesPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:toolbar style="margin-top: 20px">
  		<p:toolbarGroup>
  			<p:button value="Novo" outcome="/view/pedido/cadastro"/>
  			<p:commandButton value="Salvar" action="#{pedidoBean.salvar}"
  				update="@form" disabled="#{pedidoBean.selecionado.naoAlteravel}" />
  		</p:toolbarGroup>
  		
  		<p:toolbarGroup align="right">
  			<p:commandButton value="Emitir" action="#{pedidoBean.emitirPedido}" 
  				process="@form" update="@form" 
  				disabled="#{pedidoBean.selecionado.naoEmissivel or not seguranca.emitirPedidoPermitido}" />
  			<p:commandButton value="Cancelar" action="#{pedidoBean.cancelarPedido}"
  				process="@this" update="@form"
  				disabled="#{pedidoBean.selecionado.naoCancelavel or not seguranca.cancelarPedidoPermitido}" />
  			<p:commandButton value="Enviar por e-mail" action="#{pedidoBean.enviarPedido}"
  				process="@this" disabled="#{pedidoBean.selecionado.naoEnviavelPorEmail}" />
  			
  			<p:separator/>
  		
  			<p:button value="Pesquisa" outcome="/view/pedido/pesquisa" />
  		</p:toolbarGroup>
  	</p:toolbar>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedido/CapaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:seinfra="http://www.seinfra.ce.gov.br/facelets">
    

	<p:panelGrid columns="4" style="width: 100%; margin-top: 20px" >
		<p:outputLabel value="Número" rendered="#{selecionado.existente}" />
		<h:outputText value="#{selecionado.id}" rendered="#{selecionado.existente}" />
		
		<p:outputLabel value="Data de criação" rendered="#{selecionado.existente}" />
        <h:outputText value="#{selecionado.dataCriacao}" rendered="#{selecionado.existente}">
        	<f:convertDateTime pattern="dd/MM/yyyy" />
        </h:outputText>
        
        <p:outputLabel value="Status"/>
        <h:outputText value="#{selecionado.status.descricao}" />
        
        <p:outputLabel value="Vendedor" for="vendedor"/>
        <p:selectOneMenu id="vendedor" value="#{selecionado.vendedor}"
        		disabled="#{selecionado.naoAlteravel}">
            <f:selectItem itemLabel="Selecione" />
            <f:selectItems value="#{pedidoBean.vendedores}" var="vendedor"
            	itemValue="#{vendedor}" itemLabel="#{vendedor.nome}" />
        </p:selectOneMenu>
        
        <p:outputLabel value="Cliente" for="cliente"/>
        <h:panelGroup>
	        <p:inputText id="cliente" size="40" value="#{pedidoBean.nomeCliente}" 
	        	readonly="#{facesContext.currentPhaseId.name eq 'RENDER_RESPONSE'}" />
	        	
	        <p:commandButton icon="ui-icon-search" title="Pesquisar" process="@this"
	        	update="@none" disabled="#{selecionado.naoAlteravel}"
	        	action="#{selecaoClienteBean.abrirDialogo}"
	        	ignoreAutoUpdate="true">
	        	<p:ajax event="dialogReturn" listener="#{pedidoBean.clienteSelecionado}"
	        		update="cliente" ignoreAutoUpdate="true" />
	        </p:commandButton>
        </h:panelGroup>
        
        <p:outputLabel value="Forma de pagamento" for="formaPagamento"/>
        <p:selectOneMenu id="formaPagamento" value="#{selecionado.formaPagamento}">
            <f:selectItem itemLabel="Selecione" />
            <f:selectItems value="#{pedidoBean.formasPagamento}" var="formaPagamento"
            	itemValue="#{formaPagamento}" itemLabel="#{formaPagamento.descricao}" />
        </p:selectOneMenu>
        
        <p:outputLabel value="Valor do frete" for="valorFrete"/>
        <p:inputText id="valorFrete" size="10" maxlength="10" styleClass="moeda" 
        	value="#{selecionado.valorFrete}" disabled="#{selecionado.naoAlteravel}">
        	<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
        	
        	<p:ajax event="change" process="@this" update="totalPedido"
        		listener="#{pedidoBean.recalcularPedido}" />
        </p:inputText>
        
        <p:outputLabel value="Subtotal" style="font-weight: bold"/>
        <h:outputText value="#{selecionado.valorSubtotal}" 
        	style="font-weight: bold" id="subtotal">
        	<f:convertNumber type="currency"/>
        </h:outputText>
        
        <p:outputLabel value="Valor de desconto" for="valorDesconto"/>
        <p:inputText id="valorDesconto" size="10" maxlength="10" styleClass="moeda" 
        	value="#{selecionado.valorDesconto}" disabled="#{selecionado.naoAlteravel}">
        	<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
        	
        	<p:ajax event="change" process="@this" update="totalPedido"
        		listener="#{pedidoBean.recalcularPedido}" />
        </p:inputText>
        
        <p:outputLabel value="Total do pedido" style="font-weight: bold; font-size: 1.1em"/>
        <h:outputText value="#{selecionado.valorTotal}" 
        	style="font-weight: bold; font-size: 1.1em" id="totalPedido">
        	<f:convertNumber type="currency" />
        </h:outputText>
	</p:panelGrid>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedido/DadosEntregaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="4" style="width: 100%" columnClasses="rotulo, campo, rotulo, campo">
		<p:outputLabel value="Data da entrega" for="dataEntrega" />
		<p:calendar id="dataEntrega" size="10" pattern="dd/MM/yyyy"
			value="#{pedidoBean.selecionado.dataEntrega}" disabled="#{pedidoBean.selecionado.naoAlteravel}" />
		
		<p:spacer />
		<p:spacer />
	
        <p:outputLabel value="Logradouro" for="entregaLogradouro" />
        <p:inputText id="entregaLogradouro" size="50" 
        	value="#{pedidoBean.selecionado.enderecoEntrega.logradouro}" 
        	disabled="#{pedidoBean.selecionado.naoAlteravel}" />

        <p:outputLabel value="Número" for="entregaNumero" />
        <p:inputText id="entregaNumero" size="5" value="#{pedidoBean.selecionado.enderecoEntrega.numero}" 
        	disabled="#{pedidoBean.selecionado.naoAlteravel}"/>

        <p:outputLabel value="Complemento" for="entregaComplemento" />
        <p:inputText id="entregaComplemento" size="50" value="#{pedidoBean.selecionado.enderecoEntrega.complemento}" 
        	disabled="#{pedidoBean.selecionado.naoAlteravel}"/>

        <p:outputLabel value="Cidade" for="entregaCidade" />
        <p:inputText id="entregaCidade" size="20" value="#{pedidoBean.selecionado.enderecoEntrega.cidade}" 
        	disabled="#{pedidoBean.selecionado.naoAlteravel}"/>

        <p:outputLabel value="Estado" for="entregaEstado" />
        <p:inputText id="entregaEstado" size="20" value="#{pedidoBean.selecionado.enderecoEntrega.uf}" 
        	disabled="#{pedidoBean.selecionado.naoAlteravel}"/>

        <p:outputLabel value="CEP" for="entregaCep" />
        <p:inputText id="entregaCep" size="10" value="#{pedidoBean.selecionado.enderecoEntrega.cep}" 
        	disabled="#{pedidoBean.selecionado.naoAlteravel}"/>
	</p:panelGrid>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedido/ObservacaoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%" value="#{pedidoBean.selecionado.observacao}" 
			disabled="#{pedidoBean.selecionado.naoAlteravel}"/>
	</h:panelGroup>
  	
</ui:composition>